"""Initial migration

Revision ID: 93a01cd00e4f
Revises: 001
Create Date: 2025-12-26 13:20:45.975371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93a01cd00e4f'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('halls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('hall_name', sa.String(length=100), nullable=False),
    sa.Column('hall_type', sa.String(length=50), nullable=True),
    sa.Column('hall_sequence', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_floor_id_hall_sequence', 'halls', ['floor_id', 'hall_sequence'], unique=True)
    op.create_index(op.f('ix_halls_floor_id'), 'halls', ['floor_id'], unique=False)
    op.create_index(op.f('ix_halls_id'), 'halls', ['id'], unique=False)
    op.create_index(op.f('ix_halls_is_active'), 'halls', ['is_active'], unique=False)
    op.create_table('counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=False),
    sa.Column('staff_assign_id', sa.Integer(), nullable=True),
    sa.Column('counter_sequence', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['staff_assign_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'floor_number', 'counter_sequence', name='_branch_floor_sequence_uc')
    )
    op.create_index(op.f('ix_counters_branch_id'), 'counters', ['branch_id'], unique=False)
    op.create_index(op.f('ix_counters_id'), 'counters', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_hotel_id'), 'notifications', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('plan_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('subscription_start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subscription_end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('onboarding_mode', sa.String(length=50), nullable=True),
    sa.Column('feature_toggles', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name='fk_subscriptions_hotel_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_hotel_id'), 'subscriptions', ['hotel_id'], unique=False)
    op.create_index('ix_subscriptions_hotel_id_status', 'subscriptions', ['hotel_id', 'status'], unique=False)
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_table('tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('hall_id', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('table_number', sa.String(length=20), nullable=False),
    sa.Column('number_of_seats', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('table_sequence', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('NOT(section_id IS NOT NULL AND hall_id IS NULL)', name='chk_section_requires_hall'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hall_id'], ['halls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'table_number', name='uq_branch_table_number')
    )
    op.create_index(op.f('ix_tables_branch_id'), 'tables', ['branch_id'], unique=False)
    op.create_index(op.f('ix_tables_floor_id'), 'tables', ['floor_id'], unique=False)
    op.create_index(op.f('ix_tables_hall_id'), 'tables', ['hall_id'], unique=False)
    op.create_index(op.f('ix_tables_id'), 'tables', ['id'], unique=False)
    op.create_index(op.f('ix_tables_is_active'), 'tables', ['is_active'], unique=False)
    op.create_index(op.f('ix_tables_section_id'), 'tables', ['section_id'], unique=False)
    op.create_index(op.f('ix_tables_status'), 'tables', ['status'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tags_branch_id'), 'tags', ['branch_id'], unique=False)
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_table('tax_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('item_type', sa.Enum('food', 'bev', 'packaged', name='tax_item_type_enum'), nullable=True),
    sa.Column('auto_assign', sa.Boolean(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_profiles_branch_id'), 'tax_profiles', ['branch_id'], unique=False)
    op.create_index(op.f('ix_tax_profiles_id'), 'tax_profiles', ['id'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('counter_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('category_sequence', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['counter_id'], ['counters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('counter_id', 'parent_id', 'category_sequence', name='_counter_parent_sequence_uc')
    )
    op.create_index(op.f('ix_categories_counter_id'), 'categories', ['counter_id'], unique=False)
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.create_table('menu_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('item_sequence', sa.Integer(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cooking_instructions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('item_type', sa.Enum('food', 'bev', 'packaged', name='item_type_enum'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('counter_id', sa.Integer(), nullable=False),
    sa.Column('tax_profile_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['counter_id'], ['counters.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tax_profile_id'], ['tax_profiles.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'item_sequence', name='_category_item_sequence_uc')
    )
    op.create_index(op.f('ix_menu_items_category_id'), 'menu_items', ['category_id'], unique=False)
    op.create_index(op.f('ix_menu_items_counter_id'), 'menu_items', ['counter_id'], unique=False)
    op.create_index(op.f('ix_menu_items_id'), 'menu_items', ['id'], unique=False)
    op.create_index(op.f('ix_menu_items_name'), 'menu_items', ['name'], unique=False)
    op.create_index('ix_menu_items_name_fts', 'menu_items', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_table('add_ons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_selections', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['menu_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_add_ons_id'), 'add_ons', ['id'], unique=False)
    op.create_index(op.f('ix_add_ons_item_id'), 'add_ons', ['item_id'], unique=False)
    op.create_table('pricing_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.Enum('time', 'zone', 'inventory', name='rule_type_enum'), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['menu_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_rules_id'), 'pricing_rules', ['id'], unique=False)
    op.create_index(op.f('ix_pricing_rules_item_id'), 'pricing_rules', ['item_id'], unique=False)
    op.create_table('variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price_adjust', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['menu_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variants_id'), 'variants', ['id'], unique=False)
    op.create_index(op.f('ix_variants_item_id'), 'variants', ['item_id'], unique=False)
    op.drop_index('ix_zones_branch_active', table_name='zones')
    op.drop_index('ix_zones_branch_id', table_name='zones')
    op.drop_index('ix_zones_branch_type', table_name='zones')
    op.drop_index('ix_zones_id', table_name='zones')
    op.drop_index('ix_zones_is_active', table_name='zones')
    op.drop_index('ix_zones_zone_type', table_name='zones')
    # op.drop_table('zones')
    # op.drop_table('floor_managers')
    op.create_index('ix_audit_logs_branch_timestamp', 'audit_logs', ['branch_id', 'timestamp'], unique=False)
    op.create_index('ix_audit_logs_cleanup', 'audit_logs', ['timestamp', 'event_type'], unique=False)
    op.create_index('ix_audit_logs_date_event', 'audit_logs', ['timestamp', 'event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_error_code'), 'audit_logs', ['error_code'], unique=False)
    op.create_index('ix_audit_logs_failed_events', 'audit_logs', ['success', 'event_type'], unique=False, postgresql_where="success = 'failure'")
    op.create_index('ix_audit_logs_hotel_event', 'audit_logs', ['hotel_id', 'event_type'], unique=False)
    op.create_index('ix_audit_logs_hotel_timestamp', 'audit_logs', ['hotel_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_ip_address'), 'audit_logs', ['ip_address'], unique=False)
    op.create_index('ix_audit_logs_ip_timestamp', 'audit_logs', ['ip_address', 'timestamp'], unique=False)
    op.create_index('ix_audit_logs_login_events', 'audit_logs', ['event_type', 'timestamp'], unique=False, postgresql_where="event_type IN ('login', 'logout', 'login_failed')")
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource'), 'audit_logs', ['resource'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index('ix_audit_logs_resource_timestamp', 'audit_logs', ['resource', 'resource_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_session_id'), 'audit_logs', ['session_id'], unique=False)
    op.create_index('ix_audit_logs_session_timestamp', 'audit_logs', ['session_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_success'), 'audit_logs', ['success'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_user_id'), 'audit_logs', ['target_user_id'], unique=False)
    op.create_index('ix_audit_logs_target_user_timestamp', 'audit_logs', ['target_user_id', 'timestamp'], unique=False)
    op.create_index('ix_audit_logs_user_event', 'audit_logs', ['user_id', 'event_type'], unique=False)
    op.create_index('ix_audit_logs_user_timestamp', 'audit_logs', ['user_id', 'timestamp'], unique=False)
    op.add_column('branches', sa.Column('branch_sequence', sa.Integer(), nullable=False))
    op.add_column('branches', sa.Column('address_line_1', sa.String(length=255), nullable=True))
    op.add_column('branches', sa.Column('address_line_2', sa.String(length=255), nullable=True))
    op.add_column('branches', sa.Column('area', sa.String(length=100), nullable=True))
    op.add_column('branches', sa.Column('social_media_links', sa.JSON(), nullable=True))
    op.add_column('branches', sa.Column('admin_name', sa.String(length=100), nullable=True))
    op.add_column('branches', sa.Column('defaultbranch', sa.Boolean(), nullable=True))
    op.add_column('branches', sa.Column('created_by', sa.Integer(), nullable=False))
    op.add_column('branches', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.alter_column('branches', 'name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('branches', 'code',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('branches', 'pincode',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('branches', 'phone',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('branches', 'email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('branches', 'bank_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True)
    op.alter_column('branches', 'operating_hours',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True)
    op.alter_column('branches', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('branches', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True)
    op.drop_index('ix_branches_city', table_name='branches')
    op.drop_index('ix_branches_hotel_active', table_name='branches')
    op.drop_index('ix_branches_hotel_name', table_name='branches')
    op.drop_index('ix_branches_is_active', table_name='branches')
    op.drop_constraint('uq_branches_hotel_code', 'branches', type_='unique')
    op.create_unique_constraint('uq_hotel_branch_sequence', 'branches', ['hotel_id', 'branch_sequence'])
    op.create_foreign_key('fk_branches_updated_by', 'branches', 'users', ['updated_by'], ['id'])
    op.create_foreign_key('fk_branches_created_by', 'branches', 'users', ['created_by'], ['id'])
    op.drop_column('branches', 'manager_name')
    op.drop_column('branches', 'gst_number')
    op.drop_column('branches', 'address')
    op.add_column('floors', sa.Column('code', sa.String(length=20), nullable=True))
    op.add_column('floors', sa.Column('created_by', sa.Integer(), nullable=False))
    op.add_column('floors', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('floors', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('floors', 'floor_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('floors', 'floor_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('floors', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint('uq_floor_tenant', 'floors', type_='unique')
    op.create_index(op.f('ix_floors_hotel_id'), 'floors', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_floors_id'), 'floors', ['id'], unique=False)
    op.create_unique_constraint('uq_branch_floor_number', 'floors', ['branch_id', 'floor_number'])
    op.create_unique_constraint('uq_branch_floor_sequence', 'floors', ['branch_id', 'floor_sequence'])
    op.create_foreign_key('fk_floors_updated_by', 'floors', 'users', ['updated_by'], ['id'])
    op.create_foreign_key('fk_floors_created_by', 'floors', 'users', ['created_by'], ['id'])
    op.add_column('hotels', sa.Column('hotel_code', sa.String(length=10), nullable=True))
    op.add_column('hotels', sa.Column('address_line_1', sa.String(length=255), nullable=True))
    op.add_column('hotels', sa.Column('address_line_2', sa.String(length=255), nullable=True))
    op.add_column('hotels', sa.Column('area', sa.String(length=100), nullable=True))
    op.add_column('hotels', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('hotels', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('hotels', sa.Column('onboarding_status', sa.String(length=50), server_default='pending', nullable=False))
    op.add_column('hotels', sa.Column('business_type', sa.String(length=100), nullable=True))
    op.add_column('hotels', sa.Column('logo_url', sa.String(length=255), nullable=True))
    op.add_column('hotels', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('hotels', sa.Column('fssai_number', sa.String(length=100), nullable=True))
    op.add_column('hotels', sa.Column('tin_number', sa.String(length=100), nullable=True))
    op.add_column('hotels', sa.Column('professional_tax_reg_number', sa.String(length=100), nullable=True))
    op.add_column('hotels', sa.Column('trade_license_number', sa.String(length=100), nullable=True))
    op.add_column('hotels', sa.Column('bank_details', sa.JSON(), nullable=True))
    op.add_column('hotels', sa.Column('social_media_links', sa.JSON(), nullable=True))
    op.alter_column('hotels', 'name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('hotels', 'owner_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('hotels', 'gst_number',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('hotels', 'country',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('hotels', 'pincode',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('hotels', 'phone',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('hotels', 'email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('hotels', 'subscription_plan',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('hotels', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('hotels', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hotels', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('hotels', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True)
    op.drop_index('ix_hotels_active_subscription', table_name='hotels')
    op.drop_index('ix_hotels_city', table_name='hotels')
    op.drop_index('ix_hotels_created_at', table_name='hotels')
    op.drop_index('ix_hotels_created_by', table_name='hotels')
    op.drop_index('ix_hotels_gst_active', table_name='hotels', postgresql_where='(is_active = true)')
    op.drop_index('ix_hotels_gst_number', table_name='hotels')
    op.drop_index('ix_hotels_is_active', table_name='hotels')
    op.drop_index('ix_hotels_name', table_name='hotels')
    op.drop_index('ix_hotels_owner_name', table_name='hotels')
    op.drop_index('ix_hotels_state', table_name='hotels')
    op.drop_index('ix_hotels_subscription_plan', table_name='hotels')
    op.create_unique_constraint(None, 'hotels', ['hotel_code'])
    op.drop_column('hotels', 'pan_number')
    op.drop_column('hotels', 'timezone')
    op.drop_column('hotels', 'subscription_expires_at')
    op.drop_column('hotels', 'website')
    op.drop_column('hotels', 'currency')
    op.drop_column('hotels', 'address')
    op.add_column('refresh_tokens', sa.Column('token', sa.String(), nullable=False))
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_refresh_tokens_expires_at', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_is_revoked', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_token_hash', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_user_id', table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=False)
    op.drop_constraint('fk_refresh_tokens_user_id_users', 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('refresh_tokens', 'last_used_at')
    op.drop_column('refresh_tokens', 'user_agent')
    op.drop_column('refresh_tokens', 'ip_address')
    op.drop_column('refresh_tokens', 'device_info')
    op.drop_column('refresh_tokens', 'usage_count')
    op.drop_column('refresh_tokens', 'token_hash')
    op.add_column('roles', sa.Column('hotel_id', sa.Integer(), nullable=True))
    op.add_column('roles', sa.Column('is_default', sa.Boolean(), nullable=False))
    op.add_column('roles', sa.Column('created_by', sa.Integer(), nullable=True))
    op.alter_column('roles', 'permissions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('roles', 'can_create_roles',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('roles', 'default_features',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('roles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True)
    op.drop_index('ix_roles_level', table_name='roles')
    op.drop_index('ix_roles_level_active', table_name='roles')
    op.drop_index('ix_roles_name_active', table_name='roles', postgresql_where='(is_active = true)')
    op.drop_index('ix_roles_name', table_name='roles')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    op.create_index(op.f('ix_roles_hotel_id'), 'roles', ['hotel_id'], unique=False)
    op.create_unique_constraint('uq_roles_name_hotel_id', 'roles', ['name', 'hotel_id'])
    op.create_foreign_key('fk_roles_created_by', 'roles', 'users', ['created_by'], ['id'])
    op.create_foreign_key('fk_roles_hotel_id', 'roles', 'hotels', ['hotel_id'], ['id'])
    op.drop_column('roles', 'is_active')
    op.add_column('sections', sa.Column('hall_id', sa.Integer(), nullable=True))
    op.add_column('sections', sa.Column('section_name', sa.String(length=100), nullable=True))
    op.add_column('sections', sa.Column('section_sequence', sa.Integer(), server_default='1', nullable=False))
    op.alter_column('sections', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default='true',
               nullable=True)
    op.alter_column('sections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_sections_branch_id', table_name='sections')
    op.create_foreign_key(None, 'sections', 'halls', ['hall_id'], ['id'])
    op.drop_column('sections', 'updated_at')
    op.drop_column('sections', 'capacity')
    op.drop_column('sections', 'branch_id')
    op.drop_column('sections', 'name')
    op.drop_column('sections', 'section_type')
    op.drop_column('sections', 'code')
    op.add_column('users', sa.Column('username', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('contact_email', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('first_name', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('employee_pic', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('employee_id', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('is_one_time_password', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_locked', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('report_manager', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('floor_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('section_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('settings', sa.JSON(), nullable=False))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'feature_toggles',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True)
    op.drop_index('ix_users_active_branch', table_name='users', postgresql_where='(is_active = true)')
    op.drop_index('ix_users_active_email', table_name='users', postgresql_where='(is_active = true)')
    op.drop_index('ix_users_active_hotel', table_name='users', postgresql_where='(is_active = true)')
    op.drop_index('ix_users_active_role', table_name='users')
    op.drop_index('ix_users_branch_role', table_name='users')
    op.drop_index('ix_users_created_at', table_name='users')
    op.drop_index('ix_users_created_at_desc', table_name='users')
    op.drop_index('ix_users_created_by', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_hotel_branch', table_name='users')
    op.drop_index('ix_users_hotel_branch_role', table_name='users')
    op.drop_index('ix_users_hotel_role', table_name='users')
    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_index('ix_users_zone_id', table_name='users')
    op.create_index(op.f('ix_users_contact_email'), 'users', ['contact_email'], unique=True)
    op.create_index(op.f('ix_users_floor_id'), 'users', ['floor_id'], unique=False)
    op.create_index(op.f('ix_users_section_id'), 'users', ['section_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_constraint('fk_users_zone_id_zones', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'floors', ['floor_id'], ['id'])
    op.create_foreign_key(None, 'users', 'sections', ['section_id'], ['id'])
    op.drop_column('users', 'login_attempts')
    op.drop_column('users', 'password_changed_at')
    op.drop_column('users', 'email')
    op.drop_column('users', 'zone_id')
    op.drop_column('users', 'locked_until')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('locked_until', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('zone_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('password_changed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('login_attempts', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('fk_users_zone_id_zones', 'users', 'zones', ['zone_id'], ['id'])
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_section_id'), table_name='users')
    op.drop_index(op.f('ix_users_floor_id'), table_name='users')
    op.drop_index(op.f('ix_users_contact_email'), table_name='users')
    op.create_index('ix_users_zone_id', 'users', ['zone_id'], unique=False)
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('ix_users_hotel_role', 'users', ['hotel_id', 'role_id'], unique=False)
    op.create_index('ix_users_hotel_branch_role', 'users', ['hotel_id', 'branch_id', 'role_id'], unique=False)
    op.create_index('ix_users_hotel_branch', 'users', ['hotel_id', 'branch_id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_created_by', 'users', ['created_by'], unique=False)
    op.create_index('ix_users_created_at_desc', 'users', ['created_at'], unique=False)
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index('ix_users_branch_role', 'users', ['branch_id', 'role_id'], unique=False)
    op.create_index('ix_users_active_role', 'users', ['is_active', 'role_id'], unique=False)
    op.create_index('ix_users_active_hotel', 'users', ['hotel_id'], unique=False, postgresql_where='(is_active = true)')
    op.create_index('ix_users_active_email', 'users', ['email'], unique=False, postgresql_where='(is_active = true)')
    op.create_index('ix_users_active_branch', 'users', ['branch_id'], unique=False, postgresql_where='(is_active = true)')
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'feature_toggles',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('users', 'settings')
    op.drop_column('users', 'section_id')
    op.drop_column('users', 'floor_id')
    op.drop_column('users', 'report_manager')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'is_locked')
    op.drop_column('users', 'is_one_time_password')
    op.drop_column('users', 'employee_id')
    op.drop_column('users', 'employee_pic')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'contact_email')
    op.drop_column('users', 'username')
    op.add_column('sections', sa.Column('code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('sections', sa.Column('section_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('sections', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('sections', sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sections', sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sections', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sections', type_='foreignkey')
    op.create_index('ix_sections_branch_id', 'sections', ['branch_id'], unique=False)
    op.alter_column('sections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sections', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.drop_column('sections', 'section_sequence')
    op.drop_column('sections', 'section_name')
    op.drop_column('sections', 'hall_id')
    op.add_column('roles', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_roles_hotel_id', 'roles', type_='foreignkey')
    op.drop_constraint('fk_roles_created_by', 'roles', type_='foreignkey')
    op.drop_constraint('uq_roles_name_hotel_id', 'roles', type_='unique')
    op.drop_index(op.f('ix_roles_hotel_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_index('ix_roles_name', 'roles', ['name'], unique=False)
    op.create_index('ix_roles_name_active', 'roles', ['name'], unique=False, postgresql_where='(is_active = true)')
    op.create_index('ix_roles_level_active', 'roles', ['level', 'is_active'], unique=False)
    op.create_index('ix_roles_level', 'roles', ['level'], unique=False)
    op.alter_column('roles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('roles', 'default_features',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('roles', 'can_create_roles',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('roles', 'permissions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_column('roles', 'created_by')
    op.drop_column('roles', 'is_default')
    op.drop_column('roles', 'hotel_id')
    op.add_column('refresh_tokens', sa.Column('token_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('refresh_tokens', sa.Column('usage_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('refresh_tokens', sa.Column('device_info', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('refresh_tokens', sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
    op.add_column('refresh_tokens', sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('refresh_tokens', sa.Column('last_used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key('fk_refresh_tokens_user_id_users', 'refresh_tokens', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.create_index('ix_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_index('ix_refresh_tokens_token_hash', 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index('ix_refresh_tokens_is_revoked', 'refresh_tokens', ['is_revoked'], unique=False)
    op.create_index('ix_refresh_tokens_expires_at', 'refresh_tokens', ['expires_at'], unique=False)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('refresh_tokens', 'token')
    op.add_column('hotels', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('hotels', sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False))
    op.add_column('hotels', sa.Column('website', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('hotels', sa.Column('subscription_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('hotels', sa.Column('timezone', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('hotels', sa.Column('pan_number', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'hotels', type_='unique')
    op.create_index('ix_hotels_subscription_plan', 'hotels', ['subscription_plan'], unique=False)
    op.create_index('ix_hotels_state', 'hotels', ['state'], unique=False)
    op.create_index('ix_hotels_owner_name', 'hotels', ['owner_name'], unique=False)
    op.create_index('ix_hotels_name', 'hotels', ['name'], unique=False)
    op.create_index('ix_hotels_is_active', 'hotels', ['is_active'], unique=False)
    op.create_index('ix_hotels_gst_number', 'hotels', ['gst_number'], unique=False)
    op.create_index('ix_hotels_gst_active', 'hotels', ['gst_number'], unique=False, postgresql_where='(is_active = true)')
    op.create_index('ix_hotels_created_by', 'hotels', ['created_by'], unique=False)
    op.create_index('ix_hotels_created_at', 'hotels', ['created_at'], unique=False)
    op.create_index('ix_hotels_city', 'hotels', ['city'], unique=False)
    op.create_index('ix_hotels_active_subscription', 'hotels', ['is_active', 'subscription_plan'], unique=False)
    op.alter_column('hotels', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('hotels', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('hotels', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hotels', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('hotels', 'subscription_plan',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('hotels', 'email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('hotels', 'phone',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
    op.alter_column('hotels', 'pincode',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('hotels', 'country',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('hotels', 'gst_number',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
    op.alter_column('hotels', 'owner_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('hotels', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_column('hotels', 'social_media_links')
    op.drop_column('hotels', 'bank_details')
    op.drop_column('hotels', 'trade_license_number')
    op.drop_column('hotels', 'professional_tax_reg_number')
    op.drop_column('hotels', 'tin_number')
    op.drop_column('hotels', 'fssai_number')
    op.drop_column('hotels', 'description')
    op.drop_column('hotels', 'logo_url')
    op.drop_column('hotels', 'business_type')
    op.drop_column('hotels', 'onboarding_status')
    op.drop_column('hotels', 'longitude')
    op.drop_column('hotels', 'latitude')
    op.drop_column('hotels', 'area')
    op.drop_column('hotels', 'address_line_2')
    op.drop_column('hotels', 'address_line_1')
    op.drop_column('hotels', 'hotel_code')
    op.drop_constraint('fk_floors_created_by', 'floors', type_='foreignkey')
    op.drop_constraint('fk_floors_updated_by', 'floors', type_='foreignkey')
    op.drop_constraint('uq_branch_floor_sequence', 'floors', type_='unique')
    op.drop_constraint('uq_branch_floor_number', 'floors', type_='unique')
    op.drop_index(op.f('ix_floors_id'), table_name='floors')
    op.drop_index(op.f('ix_floors_hotel_id'), table_name='floors')
    op.create_unique_constraint('uq_floor_tenant', 'floors', ['hotel_id', 'branch_id', 'floor_sequence'])
    op.alter_column('floors', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('floors', 'floor_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('floors', 'floor_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('floors', 'updated_at')
    op.drop_column('floors', 'updated_by')
    op.drop_column('floors', 'created_by')
    op.drop_column('floors', 'code')
    op.add_column('branches', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('branches', sa.Column('gst_number', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.add_column('branches', sa.Column('manager_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint('fk_branches_created_by', 'branches', type_='foreignkey')
    op.drop_constraint('fk_branches_updated_by', 'branches', type_='foreignkey')
    op.drop_constraint('uq_hotel_branch_sequence', 'branches', type_='unique')
    op.create_unique_constraint('uq_branches_hotel_code', 'branches', ['hotel_id', 'code'])
    op.create_index('ix_branches_is_active', 'branches', ['is_active'], unique=False)
    op.create_index('ix_branches_hotel_name', 'branches', ['hotel_id', 'name'], unique=False)
    op.create_index('ix_branches_hotel_active', 'branches', ['hotel_id', 'is_active'], unique=False)
    op.create_index('ix_branches_city', 'branches', ['city'], unique=False)
    op.alter_column('branches', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('branches', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('branches', 'operating_hours',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('branches', 'bank_details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('branches', 'email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('branches', 'phone',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
    op.alter_column('branches', 'pincode',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('branches', 'code',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('branches', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_column('branches', 'updated_by')
    op.drop_column('branches', 'created_by')
    op.drop_column('branches', 'defaultbranch')
    op.drop_column('branches', 'admin_name')
    op.drop_column('branches', 'social_media_links')
    op.drop_column('branches', 'area')
    op.drop_column('branches', 'address_line_2')
    op.drop_column('branches', 'address_line_1')
    op.drop_column('branches', 'branch_sequence')
    op.drop_index('ix_audit_logs_user_timestamp', table_name='audit_logs')
    op.drop_index('ix_audit_logs_user_event', table_name='audit_logs')
    op.drop_index('ix_audit_logs_target_user_timestamp', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_target_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_success'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_session_timestamp', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_session_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_resource_timestamp', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_login_events', table_name='audit_logs', postgresql_where="event_type IN ('login', 'logout', 'login_failed')")
    op.drop_index('ix_audit_logs_ip_timestamp', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_ip_address'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_hotel_timestamp', table_name='audit_logs')
    op.drop_index('ix_audit_logs_hotel_event', table_name='audit_logs')
    op.drop_index('ix_audit_logs_failed_events', table_name='audit_logs', postgresql_where="success = 'failure'")
    op.drop_index(op.f('ix_audit_logs_error_code'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_date_event', table_name='audit_logs')
    op.drop_index('ix_audit_logs_cleanup', table_name='audit_logs')
    op.drop_index('ix_audit_logs_branch_timestamp', table_name='audit_logs')
    op.create_table('floor_managers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('floor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], name='floor_managers_floor_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name='floor_managers_hotel_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='floor_managers_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='floor_managers_pkey'),
    sa.UniqueConstraint('hotel_id', 'floor_id', 'user_id', name='uq_floor_manager_tenant')
    )
    op.create_table('zones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('zone_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name='fk_zones_branch_id_branches'),
    sa.PrimaryKeyConstraint('id', name='pk_zones'),
    sa.UniqueConstraint('branch_id', 'code', name='uq_zones_branch_code')
    )
    op.create_index('ix_zones_zone_type', 'zones', ['zone_type'], unique=False)
    op.create_index('ix_zones_is_active', 'zones', ['is_active'], unique=False)
    op.create_index('ix_zones_id', 'zones', ['id'], unique=False)
    op.create_index('ix_zones_branch_type', 'zones', ['branch_id', 'zone_type'], unique=False)
    op.create_index('ix_zones_branch_id', 'zones', ['branch_id'], unique=False)
    op.create_index('ix_zones_branch_active', 'zones', ['branch_id', 'is_active'], unique=False)
    op.drop_index(op.f('ix_variants_item_id'), table_name='variants')
    op.drop_index(op.f('ix_variants_id'), table_name='variants')
    op.drop_table('variants')
    op.drop_index(op.f('ix_pricing_rules_item_id'), table_name='pricing_rules')
    op.drop_index(op.f('ix_pricing_rules_id'), table_name='pricing_rules')
    op.drop_table('pricing_rules')
    op.drop_index(op.f('ix_add_ons_item_id'), table_name='add_ons')
    op.drop_index(op.f('ix_add_ons_id'), table_name='add_ons')
    op.drop_table('add_ons')
    op.drop_index('ix_menu_items_name_fts', table_name='menu_items', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_menu_items_name'), table_name='menu_items')
    op.drop_index(op.f('ix_menu_items_id'), table_name='menu_items')
    op.drop_index(op.f('ix_menu_items_counter_id'), table_name='menu_items')
    op.drop_index(op.f('ix_menu_items_category_id'), table_name='menu_items')
    op.drop_table('menu_items')
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_counter_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_tax_profiles_id'), table_name='tax_profiles')
    op.drop_index(op.f('ix_tax_profiles_branch_id'), table_name='tax_profiles')
    op.drop_table('tax_profiles')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_index(op.f('ix_tags_branch_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_tables_status'), table_name='tables')
    op.drop_index(op.f('ix_tables_section_id'), table_name='tables')
    op.drop_index(op.f('ix_tables_is_active'), table_name='tables')
    op.drop_index(op.f('ix_tables_id'), table_name='tables')
    op.drop_index(op.f('ix_tables_hall_id'), table_name='tables')
    op.drop_index(op.f('ix_tables_floor_id'), table_name='tables')
    op.drop_index(op.f('ix_tables_branch_id'), table_name='tables')
    op.drop_table('tables')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_index('ix_subscriptions_hotel_id_status', table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_hotel_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_hotel_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_counters_id'), table_name='counters')
    op.drop_index(op.f('ix_counters_branch_id'), table_name='counters')
    op.drop_table('counters')
    op.drop_index(op.f('ix_halls_is_active'), table_name='halls')
    op.drop_index(op.f('ix_halls_id'), table_name='halls')
    op.drop_index(op.f('ix_halls_floor_id'), table_name='halls')
    op.drop_index('ix_floor_id_hall_sequence', table_name='halls')
    op.drop_table('halls')
    # ### end Alembic commands ###